spring:
  datasource: 
    url: jdbc:mysql://localhost:3306/mydb?serverTimezone=UTC
    username: root
    password: admin
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
      naming:
        implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyJpaCompliantImpl
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect    